### ISSUE TITLE
Usage Question: trailing slashes

### ISSUE THREAD

**Issue by jambonrose** [python-hyper/hyperlink#105]
Thanks for a great library!

Is there a recommended way to ensure a URL path ends with a slash? Or—conversely—to ensure a URL path does not end with slash?

Some sites will attempt to redirect you if you're missing a slash or if you've included one at the end of the path section of the URL. In a situation where you're accepting the path as user input, it becomes useful to anticipate this and avoid human error.

While Python string manipulation allows me to achieve my goal, I was wondering if the library provides a way of handling this.

Thanks!

**Comment by wsanchez** [comment]
If you want to ensure a trailing slash, you can add a blank child:

```console
>>> URL.fromText("http://www.example.com/foo")
URL.from_text('http://www.example.com/foo')
>>> URL.fromText("http://www.example.com/foo").child("")
URL.from_text('http://www.example.com/foo/')
>>> URL.fromText("http://www.example.com/foo/").child("")
URL.from_text('http://www.example.com/foo/')
```

**Comment by jambonrose** [comment]
Hi @wsanchez : do you have a method for ensuring the path does not end with a slash?

**Comment by wsanchez** [comment]
@jambonrose No… at that point, you may need to look at the `path` attribute and make sure the last segment one is not `""`. If it is, you'll need to call `url = url.replace(path=url.path[-1])` or something.

**Comment by wsanchez** [comment]
One might argue for `url.parent()` as a feature, I guess.

(Though, in the case of user input, I'd be hesitant to assume that a trailing '/' is unintentional.)
