### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by ofek** [python-hyper/hyperlink#124]
It's been a year, and the current metadata shows no support for 3.7-3.8

cc @mahmoud @glyph

**Comment by mahmoud** [comment]
Hi Ofek! I think it's safe to say a new release is imminent, possibly after #121, #122, and #123 merge. They're all pretty small. The master-branch setup.py (and tox, etc.) already reflect 3.7 and 3.8 support.

Sidenote, do you use a tool which looks at PyPI classifiers as a canonical indicator of version support? Or are you just very diligent? :)

**Comment by ofek** [comment]
The latter, which I've also heard spelled as a-n-n-o-y-i-n-g :D

**Comment by ofek** [comment]
I ended up here earlier after recommending it https://discuss.python.org/t/add-uri-normalization-functions-to-the-urllib-parse-module/3799/2

**Comment by wsanchez** [comment]
@mahmoud Can you pop out a release?  I don't think there's anything in the pipe that would block one.

**Comment by mahmoud** [comment]
Aye aye, I'll get it out ASAP (ideally before EOD)

**Comment by mahmoud** [comment]
https://pypi.org/project/hyperlink/20.0.0/ :tada: enjoy :)
