### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by mineo** [python-hyper/hyperlink#14]
Since https://github.com/python-hyper/hyperlink/commit/cffbebae927a6d19732fe4709fd4477daf7fb44c, the LICENSE file contains the MIT license, but https://github.com/python-hyper/hyperlink/blob/master/setup.py#L17 still says BSD.

**Comment by rekado** [comment]
The header comment in "setup.py" still says "BSD licensed".

**Comment by LuRsT** [comment]
@rekado Could you make a PR to fix it?
