### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by wsanchez** [python-hyper/hyperlink#147]
We still need to ship a release with working type stubs and we have a bug fix that is blocking `treq` and `Klein`.  @mahmoud have you got a moment to push the buttons?

**Comment by glyph** [comment]
Hey @mahmoud where's the buttons

**Comment by glyph** [comment]
wait hang on *I* have the button too

**Comment by glyph** [comment]
@wsanchez I'm going to grant you PyPI access, assuming you can discover and find Mahmoud's process, since I think you have more energy right now than either of us.  (Ideally stick a deploy secret on this repo so that we can do this by pushing a tag in the future?)

**Comment by glyph** [comment]
Oh, I can't, since I'm a "maintainer" and not an "owner".

**Comment by glyph** [comment]
@wsanchez I can't add you on PyPI, but I can add a `PYPI_UPLOAD_TOKEN` secret to this repository, so I did that.  Now if you do the release automation and get it merged the release will happen :)

**Comment by glyph** [comment]
(Or anyone else, for that matter.)

**Comment by mahmoud** [comment]
Oh hey, happy holidays folks. I'm catching up now and I can push some buttons, let me look at these other PRs real quick because I assume we want those. I see some GitHub actions, maybe there's even a much realer button materializing there.

**Comment by wsanchez** [comment]
@mahmoud It would be helpful if you add @glyph and me to the PyPI whatsit.

The 2 open PRs should not block a release; neither changes end-user functionality.

**Comment by glyph** [comment]
I'm pretty sure that the github actions PR doesn't do release automation, it predates this issue.

**Comment by mahmoud** [comment]
@wsanchez Invite sent. 

@glyph Yeah, I checked it out. My process is pretty manual, but pretty simple. [It's in the setup.py](https://github.com/python-hyper/hyperlink/blob/512b4648e3b8959a27f7544537fdab88c632c31e/setup.py#L56). 

I don't think the last release used twine, but I've used twine on other projects with a fine enough success rate that I'd stamp a switch to that.

**Comment by mahmoud** [comment]
Buttons pushed, verify at your leisure: https://pypi.org/project/hyperlink/21.0.0/
