### ISSUE TITLE
URL takes any type as input

### ISSUE THREAD

**Issue by wsanchez** [python-hyper/hyperlink#20]
URL takes any type as input.   This often is wrong, most notably with `bytes` in Python 3:

```
>>> URL.fromText(b"/foo").asText()
"b'/foo'"
>>> URL.fromText(object()).asText()
'%3Cobject%20object%20at%200x100538160%3E'
```

Raising `TypeError` seems more useful in these cases.

**Comment by mahmoud** [comment]
Fixed in 17.3.0, just released, thanks again!
