### ISSUE TITLE
to_unicode() is harmful

### ISSUE THREAD

**Issue by wsanchez** [python-hyper/hyperlink#21]
I've had some version of this bug more than once:

```
>>> from hyperlink import URL
>>> URL.from_text(b"/foo")
URL.from_text("b'/foo'")
```

Note the `bytes` were interpreted as `"b'/foo'"` instead of the (almost certainly) more-expected `"/foo"`.

This is because `URL.from_text(s)` calls `to_unicode(s)` which calls `unicode(s)`.

This "works" in Python 2 and does the above in Python 3.

It seems to me that raising an exception insofar as `from_text` should be given text.

**Comment by wsanchez** [comment]
This is especially problematic in that it may be common (`request` is a Twisted `IRequest`, so `request.uri` is a `bytes`):

```
requestURL = URL.fromText(request.uri)
```

**Comment by mahmoud** [comment]
Yeah, I noticed this on the last issue and agree. Should be a quick change I can do right now and I'll assign you as reviewer.

**Comment by mahmoud** [comment]
I'm gonna close this one in favor of #20, since upon further review that basically describes the exact same problem (just slightly more bytes-specific). Thanks for the report!
