### ISSUE TITLE
adopt into the Twisted org

### ISSUE THREAD

**Issue by glyph** [python-hyper/hyperlink#3]
My authentication of this ticket filing should serve as my official blessing ;)

**Comment by mahmoud** [comment]
Awesome :) I guess I'll check #twisted-dev at some point to talk procedure. In the meantime, let's get https://github.com/twisted/twisted/pull/776 :)

**Comment by mahmoud** [comment]
Per our discussions and proceedings at PyCon 2017, I think we're all pleased as punch with the new home. Still looking forward to collaborating with you and other Twisted folks of course! :)
