### ISSUE TITLE
Add license file to the PyPI tarball

### ISSUE THREAD

**Issue by yegorich** [python-hyper/hyperlink#31]
Current tarball doesn't include LICENSE file. It is important for Buildroot distribution in order to gather related legal info of all packages.

When are you going to make a new release?

**Comment by mahmoud** [comment]
The next release will be as soon as #30 is approved, closing #26. I'll add a MANIFEST.in to include the LICENSE before then.

**Comment by mahmoud** [comment]
I published 17.3.0 last night, which includes the LICENSE file (#33), thanks for the report!

**Comment by yegorich** [comment]
@mahmoud thanks. Will update the package in BR.
