### ISSUE TITLE
Add an API for resolving a URL against another

### ISSUE THREAD

**Issue by Julian** [python-hyper/hyperlink#35]
Hi!

`url.click` appears to take a str. It seems like it would be nice to have an API that takes a `URL` instead.

(For the same reasons why dealing with `URL`s and not `str`s is better in the first place :)

**Comment by mahmoud** [comment]
You got it! I made the fix in #36. If you wouldn't mind taking a look, I'd appreciate it a lot. If it looks good to you, give me an LGTM comment, and I'll merge it :)

**Comment by Julian** [comment]
Awesome! Thanks for the quick turnaround!
