### ISSUE TITLE
DecodedURL.click() only permits unicode or EncodedURL argument

### ISSUE THREAD

**Issue by agoose77** [python-hyper/hyperlink#66]
Calling `DecodedURL.click(url)` raises a `TypeError` for `DecodedURL` arguments. A solution to this might be to check for `DecodedURL` and pass `url._url` into the wrapped click method, or to define a common base class for the two URL types and type-check that. I'm not sure whether interchanging between EncodedURL and DecodedURL is valid semantically, however.

**Comment by mahmoud** [comment]
Good catch! Definitely missed adding that functionality in the first round. I added a test/fix on a branch for this issue in particular, and I'm going to do a quick once-over to make sure other methods aren't similarly affected. Thanks!
