### ISSUE TITLE
urls will break on 'narrow' python 2.7-3.3 builds

### ISSUE THREAD

**Issue by jvanasco** [python-hyper/hyperlink#7]
Found this package via the twisted mailing list, was surprised to see a nexus of glyph, mahmoud  and cory so had to peek...

I just found/fixed an issue in a another python package, tldextract, and this one is afflicted by the same issue as well.

I'll link to my bug report and fix for the other project below (which i documented a lot and reference PEPs to), but here's the TLDR:

* Python2.7 through 3.3 store unicode data as UCS-2 or UCS-4, it's a compile-time option and UCS-2 is the default.  Python 3.3+ stores unicode data differently.  a lot of linux/mac distributions shipped with a UCS-2 compile option.

* UC-2 is considered a "narrow" build and has a max character range of 65535

    >>> import sys
    >>> print sys.maxunicode

* many punycode encodings will break during unicode decoding...

    >>> import hyperlink
    >>> url =  'https://xn--vi8hiv.ws'
    >>> obj = hyperlink.URL.from_text(url)
    >>> print obj.to_iri()
    ValueError: unichr() arg not in range(0x10000) (narrow Python build)

Catch that error?  it's a ValueError, not a UnicodeEncodeError.  

Fixing that is pretty easy... https://github.com/mahmoud/hyperlink/blob/master/hyperlink/_url.py#L1012-L1015

         try:
             asciiHost = self.host.encode("ascii")
         except UnicodeEncodeError:
             textHost = self.host
    +    except ValueError:
    +        textHost = self.host

but it may make sense to add some more tests with a broken domain (like the f*&^#*&^s link emoji url above, which has broken my indexer an ungodly number of times)

everything is explained in detail here:
   https://github.com/john-kurkowski/tldextract/issues/122

and here:
    https://github.com/john-kurkowski/tldextract/pull/130/files

**Comment by mahmoud** [comment]
Excellent! Glad you found it :) Definitely seems like a valid case to cover, and I'll get on that ASAP! Thanks!

**Comment by mahmoud** [comment]
@jvanasco All fixed using your technique, will release soon! Thanks for spotting this and putting the thought into such a specific suggested fix. I'm happy that your efforts continue to yield fixes across multiple libraries!
