### ISSUE TITLE
The hosted documentation includes no API documentation

### ISSUE THREAD

**Issue by exarkun** [python-hyper/hyperlink#79]
The API documentation page is essentially empty of API documentation:

https://hyperlink.readthedocs.io/en/latest/api.html

**Comment by mahmoud** [comment]
Haha, I suspected this was more than a scathing review. I think possibly the recent `src` nesting is tripping Sphinx up. I'll look into it, maybe @wsanchez beats me to it though.

**Comment by mahmoud** [comment]
OK there was a checkbox under "Advanced Settings" called "Install project" which was necessary for Sphinx to autodoc under the new `src/` scheme. Seems to be up. Thanks for the report!

**Comment by wsanchez** [comment]
Huh.  I have very little clue about Sphinx, because I've never figured out how to set it up properly.  Sorry about the breakage there.
