### ISSUE TITLE
Ship PEP 561 type stubs

### ISSUE THREAD

**Issue by wsanchez** [python-hyper/hyperlink#81]
Type hints can be very useful to clients.

**Comment by wsanchez** [comment]
First we need to add type hints to the code.  #80 starts that process.

**Comment by wsanchez** [comment]
@glyph This is your ticket, ported from Klein.  :-)

**Comment by wsanchez** [comment]
I'll take another round of type hints, now that #80 is done.

Before we publish the type hints, I'd like to complete (or mostly complete) the remaining hints, and then try using them in some of my projects, and in Klein, to see if any interesting weirdness comes up.

**Comment by wsanchez** [comment]
The mypy documentation has a section on [Making PEP 561 compatible packages](https://mypy.readthedocs.io/en/latest/installed_packages.html#making-pep-561-compatible-packages).  Looks like we just need a `py.typed` file?

**Comment by glyph** [comment]
Great! I didn't realize it was that simple.
